//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arena
    {
        public Arena()
        {
            this.Bookings = new HashSet<Booking>();
            this.Slots = new HashSet<Slot>();
        }
    
        public int ArenaId { get; set; }
        public string ArenaName { get; set; }
        public System.TimeSpan OpeningTime { get; set; }
        public System.TimeSpan ClosingTime { get; set; }
        public int Capacity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Slot> Slots { get; set; }
    }
}
