//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public int UserId { get; set; }
        public int ArenaId { get; set; }
        public int SlotId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool Status { get; set; }
    
        public virtual Arena Arena { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual User User { get; set; }
    }
}
