//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipType
    {
        public MembershipType()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int MembershipTypeId { get; set; }
        public string MembershipTypeName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int MembershipFees { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
