//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public Slot()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int SlotId { get; set; }
        public int ArenaId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int Capacity { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int AvailableCapacity { get; set; }
        public virtual Arena Arena { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
